[versions]
junit = "5.8.2"

[plugins]
pluginProject = { id = "com.cthing.gradle-plugin-project", version = "0.1.0-+"}
dependencyAnalysis = { id = "com.cthing.dependency-analysis", version = "0.1.0-+"}

[libraries]
assertJ = "org.assertj:assertj-core:3.22.0"
corePlugins = "com.cthing:gradle-core:0.1.0-+"
freemarker = "org.freemarker:freemarker:2.3.31"
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
projectInfo = "org.cthing:projectinfo:1.0.0-+"
