[versions]
junit = "5.10.2"

[plugins]
pluginProject = { id = "com.cthing.gradle-plugin-project", version = "0.3.0-+"}

[libraries]
assertJ = "org.assertj:assertj-core:3.25.3"
corePlugins = "com.cthing:gradle-core:0.3.0-+"
freemarker = "org.freemarker:freemarker:2.3.32"
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitLauncher = "org.junit.platform:junit-platform-launcher:1.10.2"
projectInfo = "org.cthing:projectinfo:2.0.0-+"
