name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Debian packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install --yes bash tar dpkg dpkg-dev lintian
      - name: Verify installation
        run: |
          /usr/bin/bash --version
          /usr/bin/tar --version
          /usr/bin/dpkg-deb --version
          /usr/bin/dpkg-buildpackage --version
          /usr/bin/dpkg-gencontrol --version
          /usr/bin/lintian --version
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run clean build javadoc
        run: ./gradlew -i clean build javadoc
