name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Debian packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install --yes dpkg-dev lintian
      - name: Verify installation
        run: |
          # The tools are now in the PATH and can be executed
          dpkg-buildpackage --help
          dpkg-gencontrol --help
          lintian --version
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run clean build javadoc
        run: ./gradlew clean build javadoc
